apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.quay.io/v1alpha1",
          "kind": "Memcached",
          "metadata": {
            "name": "memcached-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.17.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: coredns-integration-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.quay.io
      version: v1alpha1
  description: CoreDNS for mapping DNS Record like using in On-Premise Platform
  displayName: coredns-integration
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABnsSURBVHhe7Z15uBTVmcbnv0kmbuOOihpnjM5jYpwZs8yIMcYoEh1NjI5JRk1iXIgLiIAXQRYBFwiLgAsIBgVkEYQAKmoQENm5iILKLssF2blyb9/eu8/UW1WHrlt96vRW3TS33t/zfM+91V29n7fO+c73ne/8gyCEeEKBEKKBAiFEAwVCiAYKhBANFAghGigQQjRQIIRooEAI0UCBEKKBAiFEAwVCiAYKhBANFAghGigQQjRQIIRooEAI0UCBEKKBAiFEAwVCiAYKhBANFAghGigQQjRQIIRooEAI0UCBEKKBAiFEAwVCiAYKhBANFAghGigQQjRQIIRooEAI0UCBEKKBAiFEAwVCiAYKhBANFAghGigQQjRQIIRooEAI0UCBEKKBAiFEAwVCiAYKhBANFMhRYvfXKbFkS1JMXZUQIxfGxcD3Y6L/OzHRz7AB78XESx/GxRvGfYs3J8VXX6dFOm0/kFQUCqQChGJp8e7nCfHEzJj4+bAmccZjIfGPDzUWZKd3DYlrnguLx2dExdtrE6IhQsVUAgqkTKABj18WF798KSJO7NSgbPSl2PEdGsQNL4TF2CUJUR+mWMoFBeIza3amRPuJYXFK58J7iWLtpEcaxJ/GR0Tt9qT9LohfUCA+sWJbStz8Ulh842H/e4tCrO2IJrFoc8p+V6RUKJAS+fJAWvxmTOSoC8NpeC+jPorb75CUAgVSJHFjNPPUnJg40RjeqBrp0bJ2z4fN3oz4AwVSJPsa06LXrJg4+3F1Q620tRkYFgs20gfxGwqkRKIJISYsj4v/GtCkbLjltov6NJnxklxxkpRxP534wqFAfOSjTUlx68sR8c2H8h92YbbrqsFh8b+jI6aT/72+TXn5M6d1bhSD58ZNgeqAMCbXJsS/P2XNqj0wKWIOD0l+UCB5UB8WZoT786/yG9tv2JsW90+ImrEKd8OWBlHM+jQhYooGvrM+Zfg3cXFGl+ypYojv3gkRsbdB32Xg3mkfJ8Rl/bJ7trbDm8RhBhrzggLJwT6jIf7g6UxD/anRsF9fEReReO4Ghobe5c2o+OdHM43zhI4N4uWP4nmljkAEvzCcbvnYHxvDuOVbc1/+EbX/0TP6OAye60CIIskFBaIBDeg/7KGJ286uCYmes6Ki7lDuRoaGXjM9KloZj/lgfWHjm4TRaf15YlS8sCAukjk6sJXbkuLaYfn7Qv9pCJ8i0UOBeNAYFeK/B+ZubN8y/IU7XgnndWWPJcrTGHccSonfvxoR3yjA95GGyQUOt7yhQBTgSg2HWdWgdIbh10zDr4BjXAgHDx0WHyyoNe1QfYN9a26aYkL0fTvWbAhXjGEYF09SJCooEAUYDqkaUr72/f5NYvyyRM7Zolg8IR7r+bw4+ZxrxXFn/sw0/N+t14sintBPT01fnRD/8oTezyjEOk8zukySBQXiAg3Pr7SRC3s1idGLEiLmIZQ7733yiDDc9of2/eyzmrNlf8rM4lW9Xin26FQKRAUF4qCuPi3O6KJuQKVYzQxjLORi3oerlMJw2sLFn9hnW2Dod1oZsoSP69hg+DEcYqmgQGww7Xr98PJEw7E60E2XHiOUonAahlpuLunj/3tEXIWooUBsXlsaVzYeP+z15dkCufuBp5SicNp9Dz9rn53B75SWf+rQIDbvY+/hBQVicKgpLc6q8cfvUBnWnLvpP3CsUhROGzB0vH12hn970l+B/HFcdu+x9MskVynaUCAGXd8sbdYql3WYkt0It3y5U5x8znVKYcBOaX2d2LZ9t322BWIzuOKrXqMYQwxn077s6OPVQ0KiZnq23xREAi8QBNmQ/qFqQH7Zd/uG7FdrzpjXZonjW12TJY4TzrpGjB3/ln1WBlQ3uaSPf066yveYvyFh3ndip0Y67gaBF8hDk8vbe0hbskWdJzJ/4Spxw62dxanntROnnX+9uPG2LuLDRavte7NpiqVFl6nRgjKGVYaLwvaD2QL42ZDMFDK+m6ATaIHsOZwqS8URt6HUz0HDz/GTDzcmzTiL6vXyMVXcY+66ZLNzIKI9h4PdiwRaIK8ttYYT5bTfvxr1DBSWyteGI40cLNXr6gxrSfY3Nm/4mOa+QpF79uRbwfZFAi0QZMq2HVF4A8vX4OiWev3Fe0TFxW0H1EM0gPT7U41Gr3oPKnv2vexZtRmfqC8W53ZvDPQCq8D7IJjiVS0qKtVQPtQLzBzlIxw45Sjjg+c7tXNIjF7kvY5k096UucbD/T7cdkHPRhF26QMivLSv92Nnr8mxbLEFE3iBAMzWfLuHunEUasjjelEROZeMW5YQx3dsNFPpUZcXGblukG+FghCqXuGmF8KGcNS9CRZx5Zp0mLgyu7GPMYSnOlfa//01bJ8ZPCgQm3W7UyVXKMF6DDQ2LzBUcidCnmCI5YfPhswERCx2yidD96xuITOt3osJyxNmtUX347DM190DoURq6+761zy5Uyir1wkKgRTI2l1Jc7rUzZpdKbPxuRsIGjVS2FGQAYujrjMa8plds89B5q4KrA/pMMX/6eSHjd4i4qGT1XUp8a+9Mp8F08Kqqia9Z8eaPaeXoWB2EAmkQDq8ERG/HhUxx95u1uxMHulJMO7HLE7doewT0ehRh0ourBoxX32JxUKku4qYacrXLn86JDbuVTsmmKlCRXic9+Ck7GndbQfTeRe+eySg6fCBFIhcZ448JNXqP1Qlwbg7n/XmYK3R86hAxRKU83E3Nr8Nvgr8GRWYYkYqjSoOg5KpqudTGb6zIBI4gSAJzxmFRkGE/GRQGFh/jiGZs5GV0zDEe2x6TNkrqkDxCNXzeBm+syAmMAZOIAs2ZDcMbFdQ6DpyHWikhVyd/TT4R7kqlaBX0U3relkQS5sGTiDPL1BPaSIi7RUQS6fTYtHST8WQEZPE0Ocni8XL1pi3qcCtdxtDN9VrVMpQjlRX5G7Ae8WtffHys1oygRMIZn5UPz4MsQc3+/bXi7a/7JSVcdvulk7mfW6QAFhM+R2/Dekk6/eoRVK7PSXOqsk9ney2ICYvBk4gN2oKHrhjC4lEUlzVtn2WOKRd1e7PIqmo5obyP6rnr6Sh2ntCM278YndKnNejMJEgVhM0AicQVBNU/fi46n/t+v2n/W2eUhhOe3PmfPvsDKhVpXqNStlJjzSKdR69hxOkpyD1RPUcKkMB7KAROIGc003947fu3mifkeHhLkOUonBah65D7LMzTFpZ/ixhnQ2blz1URM6ZqnQpdsjKVyRn1zTZjwoOgROI1+pBrPV2g6IJKlE47X5FYQUk96leoxKGyiwpxQTCr0aGzSwA1UTE5n0Ybqmfz2koDxQ0AiUQTL+qfngYouduRoyaqhSF03COG1QxUb1GuQ1pMrvqs7sJZ8UWZBCo9hQxc9HycNzLVV+4WgmUQMLxtPJHhyHQ5o42o2buORfdpBQGrPXFN5vnuOkxs/I+CN7/W2uzuwekk7iLzWHvdpVIPt6RMme/nOe6TZV93JIJlEDQKFQ/ujRsOONmwUcfizMvvCFLHLjNa+14uQrQ6QzpJG7gc1w9VD2jhiGXavMeBAN1RSwokBYMZj1xpVX98DBMAavYsXOv6N7nJXHN/3QwrceTI0Xdrn32vdkghRy9SLmrpUi7clCT0rdAer3qfGm/HRNROu5TahOesRzd1HFLJHBOOtY2qH54GMSzaLN/6RRf7k+ZSY86UZZq8BtUSZWLjc/xrYfVj3HafROiylWKWBHpPhdrTIJG4ASSa0oTdadQDMFPVmxLmjlSqtfLZUi5/+ngkLh9dMTwHcLiu45NPlH4bf6GbEEfaCxshSR6OxXulJnzn8ieyGjpBE4gV/wld0NFmZ7GaGEigQh21usfg8bs5RO4DfWpsEhJNXTafjAl+syOKZf2YgSkyxbwMlWBbfhsbRzfF+oCB43ACeT20bkbD3wHVFzMBwxPsCkn6mth+Pb0u7Gcy1PnrffeSxBR8LFLik8KzOV3eBlKms75LFuNuwzRy+Aq1rYEjcAJpPuM3A0Iy2NzgdkcLFK6YmC24DCMm7A8njOFftnWpDl0kutTsJXawk3F+0BzPkuUVHER08GqLGAUqYOAus1gsmKLZ1yObQ6O69ioLMn5woKYaDPIWo9++TMh7R7o0rAcNp+13Fv2p81Kh1Nqi+85UEpIta96oXZx75CZluLm6Tkx8arx3QWNwAnkk7qUsmFIQyVENyGjt8gnyuxlmIZ9/4vcQvFiz96Donb1evHV7gP2LdkgpwoVUlSvX6hhnb2798OxuxpjEAicQOD06naFVW3n/Nw8f1JHrjR6oLeMHsVjrVUWm7bUmYWtnRXgr72pg/hi/Vb7jOa0n+Bf5RT0GCSAAgFeDjIqE7qBoC7oWfrQxWlIuYePopqhkmD/EKSyOKP30lp950axbsM2+8wMiOGoXq8Yg8/hZ0zoWCWQAsHVUdUoVDtBvWE44qpz/bBv9wiZATnVGvLb7uquFIc0bJPgBiWG/KxWjyJ29cEtqmgSSIGs2pHthxzfsUHZUBETcZ/rtw13rfUONUXESY6901WGYdeh+uzI9mX9C4+B6EzlkwWJQAoEPoA7on7zi9mXSji+5UwTkTZ+WXMHfnvdHqUo3LZ+43b7ERmKjdjrDJXfg0ogBQIem97cof3r4uzhFYJ+znPKZS8saP7akWhMnHru9UpRSEMP09CQ7TNB/J/uTInBc+PmGnJd7lm+1nNWcHuRwArEOd2LXkJVMf0HHuvX/TZUWnFzz4NPK4Uh7bd397bP1IMaWEhcfNbwdW40esliYiX5rG9vqQRWIABbEKABqMpqIljobijlMtVyX8Q+Lvnh75TiuOiy20Xdrr32mYWBeAZKpaLHRFVJVJbHUlrV+4KhQkuQCbRAMPZHI+j4Rvacf649M/y2hYqqhai71f6RgeL0C9qZwjjtvHZmz6ILGBYD9hVBrSyIBkWqMTEhA6OTVwYveu4k0AKJJtLi/CdCYuKK7EZw19jKVUdsVaMOUEpQnwtiice9neVP6pLiVyMjZobvxr3+DIkQOc+31m9LJdACAZhiVVUgvNCxt0Y5Des7Nu3Lnl4uhIih7x890/z9IoZxz/iIuZkO0uNJcQReICjk4F52etBwCZyNrVzW7vmwMjGwEBCNR0aw6vmdhs10UH8YwVAUZwh6z5AvgReIikWb9QmNpRpmzZA6rloPDlYbw6V8ZIMFWsUGMpGPdtXgJtF5WszsZdbsTGlTX4IKBaIAad2qRuWHnd41JKav9vYlnnnX2scQM2xIcwkptorbbAzJnpgZFacUsPVzPoZsYExtuyP7QYYCUdCvTLV12xiNHtF5FVjeqto2AetO0GgxHPv5c2HfEyfdhpQb7OFILCgQBbm2Ui7UkBnbe3bUcwiz+3Ba/KQKKsLDsGSXZKBAFNw51r/Gelm/JrF8q7dHjCh3PnVxK2E/MXwSOu/NoUAU3Daq9BgICj9gGwRViU+AnKkhc+PaKHYlrVVNiNPBCigQBe98ljCGReqGlI+h7I4uWLe3IS1uKqI0T7kM9bWwqSfJhgLxYPi8wh11bDCDyiI6Zn2aEGd77FFytAxli4gaCkRDPiWCYEg2RCzBK64BUDn+aG/uqbIn36JTroMC0QA/Acl7qoYFQ/mf11fEczq2k2vjonX3yqSuFGJBrHNVKBRIDiCSx/+WEQmc6tvHRMS89bmrk2CjzLYjyr9ktxjrPZs9Rz5QIHmC2rXPfRAXew7nUIXBPsMJ7/hG1HR+VY3zaBpiMu4VjMQbCsRH6sNpc2r3VJ9TQPwyrCZ893POVhUCBeID6DH6GM6uH6U/y2WozL5lP+MchUKBlACWrrafEDYrsqsaZTUYhnm9ZkUDt/mmX1AgJYBiBpWom1WstRnUJFbXsdcoBQrEB5C+/r2+1SMUrIacuCKR15oSoocC8QkECV83GiXq7qoabSUMy3dfWRw3S/0Qf6BAfAaxkfkbEuKOVyrjmxzfsVHcNqrJnJ3KtWEPKRwKpIxgM9CJKxPid69ExJmP+dezYFUiRPHa0oSZwkLKBwVSIXB1RzXH0Yvi4sFJEXHNc2FzJ1rdVs0I6mFn2auHhMwibyi4gMLbXLNROSiQowyEczCUFlsPpMzyQzDsr46tnHXJj6QyUCCEaKBACNFAgRCigQIhRAMFkgPMHn2nV0iMbmHLUh+wP1c5l9uiQv55PULi+uHZ2zscK1AgOfi1XeHkL++3rAVGt9qfa2AZP9cwe/tsFL47VqFAclBtApmxOm5m5769Nv98EvQSeEzttsxjKiGQXV+nza2kUSz7WIUCyUG1CeS+Cdb7wYrFfGkzyCoxhCGPpBICaQlUrUBQtHnUwri5dhpXv6fmxMzNKSXyqrh6h3VV3LwvZR47G7J87MJNSXOlH8p/Tq5NNMtZQj0o3NfHOBfn9XvHet7dxtUPqAQyaaV1jixCvWFPyiw6jdtgeF3sXiUj3ijIhtufeTcudtWnRX/js3z+Vcp8bdw+xXhPaLz4H/umI2ioYtyy+JF9E1HcGufnWgI86O+xI5UbUYsLj0ml00cEgg06h35gvfZwY0iEoKUEqTJYnov7YPhceJ/YMkLy93XW94f7sWhsSm38yPeLHgu3v7I4UwoJO1nh88vnQ3Il9jepVqpWIEj2ww/oNGySj70DgbwqjltqfbtzjR8Kx0jNkHzjIWtNOEr9y+eAYWwMPtyYbLbNM6ohIr0D/yMtBLgFgr3UT+5knT9/Q9JoRMJzJSEqsIMlW6z3dppxnkyLR30sNCj8735/aNCqjFzsWus8D4ZtC3QgncX9mKTRgqVA3K997bCMQ616Pdg9E6zPNecz63O5bbAhSoDGj+Orh1r7HG7Ym1ZWkrzffr5qpGoFgoaOL2+ccSXeZPQOSOXG8Zv2VbsQgeAqikZ6h11z9zdjIub92PkVxz8e0GTWyJ1pNFopGC+BoCfD8ZWDrIa09EvrdbEVwcptKbPBopwObrt6qOWcSoHA7hwbFVNXJcRXRg8lBYLyQR8ZvReKzsnzNigqM6JKCrZZw/34DHjeUFTfg+CKfWk/67vrPsN6TNrRg9z6Mm5LmT0FjrEFguTkRy3hT1geNz/X4LnW+724t/XZe86yjvEcqFpfY2+tje8MuAUy3ugBcXy50Quixx9ljAJwjItGtVK1Amnd3WooK2zHEvWpsEn+Anuzy0IEguEMwPAFx8iEBbKxS8GAE+3eQSWQJmPYJze3lE4ynFAcYzpT8vpyq6GjGDSQAkFqunM4IQWC/RAlOIZBDCrK5YNgywMcY4muRH4XaMzgg/XW57qwl/W5HrcvBPK9zF6TMH8jDJ+AWyCvLrUej60cAIbMOP+P4zKfv9o4ZgTi5mgIZORC6weGHyBrYhUikDO7Np/u9Esgb69NiFuMnsVpuKBIKiUQN7kEcixQtQK5qI91pf7T+IjhRMbMIcA6R6OptECeNZzwi/pYQ5WpH2eczmoQCNLgMbZ3GqqYSEoVCEqmPjotan5vOJYCwV4iOMYqSjj6qBuGnlVePNwCwWQEjnHxGzw3bv6uuK2aV0BWrUDwZX/TbuDS4KTLq1mlBYKZmlZGA8f/cO4l1SCQXJQqELdJgcBPOqtb9gTFwPet13ELBBuWXmJf+JyGi2C1UrUCAdh5CQuEMMxC5XR8mZg+BZUWCIZY0vnG/iGSIAgEWzlg5kuanMYF8MvwXeF3qplufR6UWwVugYB4Mm28lnW+nBg4v0fmN6s2qlYgmIPHclJ8oeAXxrgVX+bYJUdPIFsPpM19Q9CzySJsQRCI7LXxm+B7QdwHIB6C3yhkPYWYuMJq8NhLEbgFgqEUzj8csX5TzLDh/nO6USAFc4k93pezVt4CsY4RsMKxSiC4YoEB71k/mE4g2MQSt6kEAm4Zab3uo1OtH72cAokmrG2eYXDEgRRIhymZx+RCfldY7ispRiCI3eAY0+JAfn/32nGMXAKZZvhuOJZT5BRICciIMfYLROM8157VglMHENCSXza6dvwIOFYJBAGvmhmxIyV5sKE+GGrP62Nrgq5vRpvt3+ElEClE1N/FFRVDBRyjYfWYGTP327h2mPWYtnYWa7ECwRVaHqOxAbkdAwSJx+2wA6c65Hd1aV/rtZyRdJ1ApM/1B+P7wueSgUPZ4OFk4xgxKsSabn7Juh8Re+AWyDt2YLFVV+t14XvgGFnF1UrVCgTDARnVloZe5ZDV5syUEfyY8r7v97cagUog8j4YSvFguhIgpQNXL3kfNsJBrAL/ewkEMzQyGo6IfMIYkEtxOg3PI4OafgoEgjzdaGDy9lyRdIDApOwZYc5Iuk4gmJhwZhrAjjM+F4rSAWQ1yAuXNAQaEXAFboFgKOauG4bhKmbAqpWqdtJRFBqZoGgUnxl+hLuax/5G6374GPJqvmZnZoZJCgSNCPbxjqRZgd0JGiECVijR2WT8gPiL54HzCbbst57XmfO045B1mxx64B4UW8BtMLwnpKRIGqPW+c5cMoBoOm6HbyORzxEx2hicYXnsfD40NAgYt4fzbFsY+8vvEpF09+fC94Bjd+btzno8JnnkPhSTcIJNSj81vnPr/mSzMkR4z7jdmRWAQhT4vXD7qu1JcyKmmqlqgZSK20knpFAoEEI0tGiByHR3DNUIKYYWLRBCSoUCIUQDBUKIBgqEEA0UCCEaKBBCNFAghGigQAjRQIEQooECIUQDBUKIBgqEEA0UCCEaKBBCNFAghGigQAjRQIEQooECIUQDBUKIBgqEEA0UCCEaKBBCNFAghGigQAjRQIEQooECIUQDBUKIBgqEEA0UCCEaKBBCNFAghGigQAjRQIEQooECIUQDBUKIBgqEEA0UCCEaKBBCNFAghGigQAjRQIEQooECIUQDBUKIBgqEEA0UCCGeCPH/T3Y71dUCq1oAAAAASUVORK5CYII="
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - cache.quay.io
          resources:
          - memcacheds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.quay.io
          resources:
          - memcacheds/finalizers
          verbs:
          - update
        - apiGroups:
          - cache.quay.io
          resources:
          - memcacheds/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: coredns-integration-operator-controller-manager
      deployments:
      - name: coredns-integration-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/linxianer12/coredns-integration-operator:0.0.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: coredns-integration-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: coredns-integration-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - network
  links:
  - name: Coredns Integration Operator
    url: https://coredns-integration-operator.domain
  maintainers:
  - email: wdrdres3qew5ts21@gmail.com
    name: supakorn.trakulmaiphol
  maturity: alpha
  provider:
    name: supakorn.t-thesis
  version: 0.0.1
