apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.quay.io/v1alpha1",
          "kind": "DNS",
          "metadata": {
            "name": "dns-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "cache.quay.io/v1alpha1",
          "kind": "DNSRecord",
          "metadata": {
            "name": "dnsrecord-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.17.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: coredns-integration-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DNS is the Schema for the dns API
      displayName: DNS
      kind: DNS
      name: dns.cache.quay.io
      version: v1alpha1
    - description: DNSRecord is the Schema for the dnsrecords API
      displayName: DNSRecord
      kind: DNSRecord
      name: dnsrecords.cache.quay.io
      version: v1alpha1
  description: Chula Software Engineer Thesis CoreDNS for mapping DNS Record like
    using in On-Premise Platform
  displayName: coredns-integration
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAACZDSURBVHhe7V13uBXF3ea/LzEaE00MYPnURIiRGE3sWLFHP7smmkSxaxBQkV5FEURAwQIIKgIKFroiTUB6FWmi9CrS8d7Tz7l3vnn3nOXM2Ts7O7unze6d93neRzlnd++emXmn/kodoqGhYQstEA0NAbRANDQE0ALR0BBAC0RDQwAtEA0NAbRANDQE0ALR0BBAC0RDQwAtEA0NAbRANDQE0AJRBPEkIeF4mvFU5kONskMLpMiopty8r4p8vjpFXvsyQVp8HCV3DIqQS3qHyR+6hMhvW1WSnz9VQf7nqcocHtWi0vgO1+DaOwZFSYuPYqTfjASZtCpFNuypIlV4uEZRoQVSYByOVJPJa1Kk04Q4uaZ/mDbyUI3GXygeT5/dpF+EtBsXIxOpaA6EtGIKDS2QAmDNrirSc0qcXNk3Qn7RvOZoUCpi1Lm0d4R0/zxOvtlRlXk7jXygBeIRm+i06YXJcXJ29zC3sarAhl1DpOukOFm3W4vFK7RAXCBBF88fL0+Sa+nU6WdlHCm88Iq+YTJiUYJEE3oa5gZaIBLAuuKVaXFyaid+4/MTT2xfaUzB9ldqochAC0SAQxFCnv8sTk5oXbyFdrl43LMh0nZsnOyt0EIRQQuEg2iCkD7TE6Rum+AJw8rjnqk0OoGKmBYKD1ogFoxdkSRndFF34V1o/urpCtJmbIzs01MuLrRAMsBh3k1vRriNKIg8pkUFaflxjOz+SQtDBC0QigWbUsahG68hBY1HUWE8PCJKth7QwpCBFkgG6/dUk+c+iZHfPcdvWEEgzFXW/qDPRNxAC8SCUJyQt+cmyLk9gjOiXNo7TOZu0BaQXqAFYoNqOgOZsS5Jbh0YIT/nNDo/EJsNHy1LGr/FKzbsrSKPjowZJ/K10ThSC0QC3/1YRf47KkZ+9TS/IXrl0S3T5iCNXwmTxrSXP/P5MDmmZf4n9Me3qiS9psZJNJn5AR6A39x0WMxYs5jPveXNiHFoWptQawQCM5F8gUM1nBnUbV2zUcoS5uvojRduTpFYsmZjw3su3VpFXpwcNwTDe4Ydf/ZUegGez87Uhr3VVBjRHGGwxNSzNi3wa4VAFm1JGSYW6AHHf5OkjTC/Cq6MVZMBM+Pk9M7y65QGdLozammSpFyskTGlwfvKGETCZ2TRFu8LcDT6R6i4ZKyRT+lQWWushQMvkJnfpYzTYmsFd6MjwfaD+QkFXoDvLUiQs7rZN2AYNeK8IRz3/rfgYdhlYpzrWFWvbYgMmZvwvD74kY42eD+ci1ifLSKcueZtDP7CP9ACmbo2SY592r7iMY2Ad9+0b1OG559XYFTA6HDOC7lCOZquJz5cksdCwAJ4Ev762fSzMZ16nC6evRod/hStNjqJ457xvluHd/mSdkBBRmAFMvP7lKtFdSM6jXljdoI2nMwDPAC9+KdfJ8lf6TwdU5UJKwsnDhOz16eM6dT8Td4aZpyue96YlSAn0pGHVw5uCVOVWbSsg4pACgRrDq8n43CRbfVpjGza531MgVBUPJDDekY0HfRKjEKLNgdTJIETyPd7qo15Oa8i3RDz/bsHR2lP7f/F6PJtKXL1a8W1M6vbpjKQp/SBEgi2YRsWoYe8tE/EmDq52YFyg4qKMPlh934SjcUznxQGe2h5YJ3CW9wXg7/vFAqc8WNgBIKdnqteLW4veebz6R0j+Ivkiz17D5LOL75NzrrgPnJ03SYGjz3xanL5dU+Swe+OJ7G49z+CbWyEGCqHoxcOPfM5oFQNgRFIs1ExboUVg9gmRnyqyljmj7vExMlzSf0GtxwRBo9/u6wp+X7Dtswd8viKLuLLbUf25IceC0ZBBEIgCEbAq6hiEyfqOPE+5ML8YsLnc4yRgicKK09rdDvZvGVX5k4xMJ16YFhMiWASOLMJCnwvENgMWQ8CS83fPRcyAiFUOHScu388QOo1uJkrBjs2ubkZqRZYG2LH7O25SWXM9LHtGyQ/d18LBOuOC3uWdzrBcv0e8Sq+fde3uCJw4pQZizJPqAm4yvLepVxEaNUgwdcC6TIpzq2kchA9p5O5R4Nz7uYKwImPNe+VeQIfJ7Xjv1OpCcuBrfuDtdXrW4Es315V1jCfVp7VLZR5Mz727jvEbfwyvPCqhzNP4ePilwu/te2Fj40MzuLchC8FkqSd1AW91JlagZjqibBp805u45fhn86/L/MUPq4p8iGgDH/RvJJs3KsPCpVA/5nqTK1MYmtVhMOH6RSE0/hliLMRES7rU36BPDhcvPbwam1cbvhOINjOhKk1r5LKSZi3OOHcxk25AnDis+37Z57AB06wee9UKh5Fp7oIeiECTOr9uLvlO4E8PlLd2FV7HUzP+/T/gCsAJy5d/m3mCTUB6+Ny+8w/5DB6YOqFKRgOc/0GXwkExnB2rqAqcNIqsY1FKBQx1hM8Edjxgce7Z+7mA74svHcpFbFR4rT2wOLduLZFJVn3o79GEV8JBNa11gpSiQjs4IQVq9ZLHxZefPWjxtpFBAS9O7kD/31KQRhDirBlf7Wx/Wtef88Qf52T+EYgMNlWPSdHvdYhEpHIv7F23WZywZUPc0Vh8l8PdyOHfxKLwwRSr8HMhPdOxeQvacPfflA8ejw6MrdTQx1+vd0/u12+EQh6HragVeX7C+VMWZPJFPl47Jfk3gc7k0YX3kf+90+3k/OveIj899lXyILFqzJXuQM8GBGcgvdexeBzY8Q2V+m1R81OzU+jiC8EghRipfJpyIdI2nkgXN45NnaKSjEVRewtp10pLN5596Iu/ZIWzhcCwdyeV9AqEecAKuU3H74oSX5TxO1w5GcU4VsqANGGil9M4n0hkL+8qIYphR27TIzlFd6zWECi0cv6FL7ssCmA2GAi/HOoeBRDQI39Pkhb7QuBfLMDsa3UMi0BkXZ58NwCuBe6AA5KQVnALAfRIAu5PY7g3iLATk5mQwVOZ6rDN4t0RORQaR2CHRz4qZcSOw5Wkb+8ECb12laS0cvc/W14GhYiCenZ3SsN0YlwwwC5UQuhllQceVn4RiDAq1+qYYMFB60Z6+QXHIXwYUc8rFM65I6i9wwJ09FEfrGLKc1tA/NbwE9eI/7dKBfefXb0Gt+rVPCVQADErOIVdKkI78GFLioVMWxP65g2x9h5yH13idCg2KSwGz0RAA6jqyzwBr2nxT25Ctz4RiT9EBvAIPEil6b3Moer5YTvBIJKeGBYec5EYJCI+bUsvqC9LbZDzfsxLYNQEIlQFG0+mao2Et488SFSLsg1ZER1dxMVEs9H8Anes3jEGmb1LvFvR5hV3r0iokwLEXm/WPCdQAAU6O2DSiuS+m0ryCqHBsLi3fkJYS8N4SCYG+yU2o1LE2YbOEvxaq3coAsd3TbLvyNGpyb95DY/Wnwk7ukjdBrp1ap4uovpaqnhS4EAmNfLLgbzJaYxTr0nC0Q64T2nFIRBIAJIYBSSAWJoITcj71km67V23pJ9ear3yDLNHcRXTigpEOxsIF+5E8JxQq6jPS6v0K1Eb47zlJvfipB7h0bJnYMj5NI+YXKCQzQQTAFW7pTr4TD9Q9AC3nNKzSb9ImSHi/QOmB6ZkeOtHPiV+FAQI1E+h5Knd5KzOSsHlBQIGiQatNOOCQCRXP86XyTIeXH/e1Hy2eqk7cEWPl21s4r0+CJuTFHY+7Egl11zoCe+v0xrIztC3EiZIAsYhJ7eOfcZF/QMOYZcNc3Z86GqcX2VFEj/menhGj2azJwaFrTIHmUWNnZ84FjldtcIDeGDxQkjcxQOJmFKLoMYHewwIpl/XyXiwK71mJj0QhijweV9078FOUgWOZQ/RFWI8ymknlARSgqEbWzoxVfscK5d2EHd907U6AHzTXmMAHDLaMXLAIvTmxhxqsrL+4alO4wo7XCwU/jYSPG2GKbCV/YtjIWDqha+ygkEhV6/XW6hY5EsMwRjBDgQzvyjBEBatetfV2taJSLKESnpZIB6wPRVhA8Wu9/WtSPeTUUoJ5CNe/mRAmEgp5KJNEYOu7WPysR5Rt8ZibxNPJDCzXqyny9hXKkalBMIEt/zCg+ESGBGXW5gzfH3N9SfVon473ciJJRHYtHWYwq/lf3xcnf2ZaWAcgLpOEG8IwKPOTcHdoUGFrt3Ku4bL0sE39t2wH1ZrtxZnKiWnSY4zOnKAOUEcttA5565XpsQWewyJ3g4EiNTpi8kr705mvTqN5y8/8FksnHTjsy3ciinmUuxiA5HdrcOqKJzsysyu1yFJgwpVYNyAvljV7l5PUw1ZqxzHpKRqanHK8NsI4ncdFcrsmrNxszVYrw8Vb2IjoUgbMSw4JYBzpMa9y7O2quhQ3zjckApgWD64sax55ERYhOFAwd/Ilfc+CRXGCyPP/k68un4WZm77PH56vLGoComj25ZKb0NXEEX6LIWDG6IulfJbRlQSiBIvcwrODsiF7odUqkqct2tT3MFweOvTrqWzFu4MnM3H0k6x8J2JO9d/M7OE93ZQyEPYTEMRjc45FgpNZQSyGza4HmFxiOmWKLT4aHvT+QKQcRzLnnAEJYIdpE6/EwE3sbOnFug/GHXxnumV8IVQCUoJRA3/gTX0iFeBDR2ngicOHnqgswT+Bg6rzz5EItFRD3MJ5Ab3G/vL2DQOrQBlaCUQEwbLBk2H22/47F1+25u45ehUyT1+RuruO/jV8JIM19g0C3U7h7SV6sEpQTSdZJ8TySq2FlzlnMbvwxvv7dt5il84LSX9z5+JPKKOAVgQLAHGVu4QolEtQy5SgkEOSR4hcYjzCXsMPOrZdzGL8Pb/ikWyK5DwRAI1nBOUdlhTvKHLiHDYFTmrAROWv96J78zEifPxVJDKYE86sKvQDSCbNn6A7fxy7Bl29cyT+HD7U6bqhy2wHkq8wSTiwWRXGQMHbFwv+tt7yMJfOtVglICcbPYc0o3/OeL/8MVgBMnfTEv8wQ+5m30/1kI7LCcAGc1a/A3REOcslbicJZegggo7L2yxAikEpQSiJstQ1jSijDonXFcAYgIUSHqugiD5/j7NP0MOmU6FBEfCO6vrLbNOYJT98lrnEUSogO86Xjlhv9QzC9EKYGgcHiFxiMif4gWmGjoTW5uxhUCj8eeeDWZPffrzN32KEcejkIRW7oyNmwISMe73+QvW1YaIY2cgEj3OGPhPcOOqjlO+XYEAbHDIgJykze+5jGuIFj++uTryIefTMvcZQ/4UJzakf8ufmC/Gc47RO8tkDuLOpauSWTC9cB8xernLuK9Q/Ui3RZutwllEtdHojHS+cW3yQmn38gVR5P/a06Wrfguc7UzNtNF+l2D/ecoBRN9Jyep9XuqyPGt5Ht8BLWbI+HeDG/Qum3knosgGypBKYEgkiCv0OyIRSOCDMigoiJMxn/2lWHq3u2loeTt98YbqdC8AjFo/+py+lAuNugSJgcdEvvASNBt2FAQ4X6WbHWetmG0R5QZ3jNYOuU8LDWUEohTADMenxpdvgLF4RhMT05qx383FXjsMxVk+XbnXh6RT3j3yxDhhWRiBoxcnHRMi+CU1q3UUEogXiISIuSMG4efYqCSahTRDNk4vKpwmETOxM9W558gFWszGe/Ebp+J6xjlqBKUEsigOd4MAXHaq0K2IiS2eZqOgtgK5b1nvsR05hojnm+UtB0bI21or4+DNZiM8P5mM4nRdfvBalK3de59XonIlU71gG9F2acGfqVtsWyBcKO8QpMhUo3BkafQcLB+5wI9KebShfDbxkIYQfDm0Dk8/FHsgBBEyHKLxThGVbjFOjkfxZPVhrh4f9crr6R/F74iIuCM5IJe/PXOGImQs6WEUgJZvCW/U2ocTHlp0HYYMDNhHKx5rTQYNsJ8xotQ0MiRO0N2E4IF1gMy9z3rYc0nQwTwE2jZwNYD1XTtUvPeRZvLO122QimB7KaVai0wN7x7cGGixmEkeoROXdhnw/9ENoi1FZv3p5PgyE69cIpdbMchUXilQlAmQsmX36VquFj/cLjws4B8oJRAsE9vF2HciYgjm284oBTt9kYtTdrmuUBlYuoEIXvBrkPVpM3YOF1L2G8PYx7vJiq7F6yhIwyMD3l/v5Acsch55O3FBMLAdFIteSgmEMBubupEryYKECWC0SG/xZnPy/1tHKZhtwUxfL0AZxK9pyVqZHhCRBcvUyo3gB3WWd1Kc9CJEdNpyoRfa+ZNPO8lHdXEEThJtRa0DJdtE48eB0LV5HxaAQg0/Z/3IsZOylWvRow9fN7zZIiYUm/MipMYXex6ARbRIxcnjAM69OjFjhqJEZKNgl8KIjwpRk4RsPOFUVvGyrjUUE4g6Fl5BS3i9QOc1x6dJxbPCheVi5RrTt55Ijg1okJg0qrirjvsiB1Gpx21+RtTpM90tbZ4AeUEMu1b9ztZU9aKSx/m26U4xMMUbfii/ITihGo6J9y+cw9ZuWYD2bZ9N6mqkv9jeC+31rWFokyatUKkyy40lBMIhls3p7p/RjL6zL12cDq9LTSxlsAJtigskVvAMrlDt4Hk92fflWNsecqZt5NWHfqTXbv3Za4U45Pl5RlFwA+XqnXGIQPlBAI0oo2eV8A8vumQmQhbtrKWpIUmpl5Yo+AQLx/MmL2UnPzHW3OEYWXdM24iEyfPzdxhDxw2ntqJ/77FJjY3vvuxuOusQkNJgeDkmFfAVmJL2Mk7rv/M0o4ePCIaI+zMMNVziznzVxihUXmisBJOX1OmL8rcaY9ipC6QJXaqnE7aVYKSAsFQzCtcK50c/HGqDlNv3r3lIAQNX/oNe+WEEgpHScNz/sEVgx0x5Tp4qCLzBD68rPMKSUSv8QuUFMiPP1VJrUOcnHXKtWvjRJiRIK6tU5SQt4aM4YrAifB5EeFgmHDfq1RE3cr4tasAJQUCXOIQYh8WvE79cKn3/N3yVLpGEeH6257hCsCJF1/9aOYJ9ih3EG6Y03iZcpYaygrkBQffkI7jxcM0zDWOasG/VxVe2kd8fnNiA/HC3I6IVO8UhPucF8o/9UQMAtWhrEBgV8UrVJNfO3jJsTY+qtIpAPdxJ8ktznmEL74I5/VUY3TFtrPKUFYgAM44eIUKE3QnwOiPd69KdBpB/niuuwW6SWz5OuFwpJqM/yZJmo2Kkga0PHnvVwpe/Zp65iUslBaI3TQLfgwiwCydd59qPK1jZeaN+Wj6xAtcATjRKQA3D/BdeWd+0rCHgo0Z732LwVe/VMvF1gqlBYJK4+1mOcVjer7EJ+deid8mijaCA0KeAJw4duLszBO8wbRwRhTJ+9+LGZsJvPfPl3Ak8+o6UCooLRAA83S2UBHqx+mgSZX5tQyxFS3Cnfe154rAjtfe0sKVfZYstuyvMs6nEH0d6aPd5JK04x2D9CI9b1g9325wsNxFEAL2etXpFAcKiUjPv+IhrhisbHTRv8kPu/dn7iwu4Fc+d0OKTpES5F/vRkjDriFXNnQgAmSrDuUFEqcdLOtY9JJDRqR35vsrRRpiDDsFmzh0uII88Hh3rihM3n1/B8OgsZw4RNfbs9enRdN0WNQwKznGxs24Ybewo9+6ClBeIMBLU7JrCiT6FOE/dM7MVoQfiNRzMlixaj1p1+Utcg2dRv3tsqZG2NTnOr5OFi9dm7nCGaVuk4icsmpnleHK3HVS3PD8xO7kW4qF97GDLwQCE3hYgmLei0T2IljdWFUnetLvS5T6GAEREAUSZi5ooBscMkxp+EQgAEJjwtlHhM0+yx+ImFR7K0rXp6P3tr4DzpQQExlrvVK+i1/gG4EgmMGTtCJFKHYom0IS5w2REs4yELGQ9x4sschGJwSL40+/ThqRIms7fCMQwCniR/vx6p9/IDwRfEOcUhEUEthK9hK8DoKB8xrSTCCnIaaCpXxvFeArgTgBEUt4Fa0KEQ8L5h2lxGg6qsqkHZBlvdYhcjMtZ1g5IBbAPh9Y5OaDQAnk9DK5ksoQOzduwvrAWiCfMKo4TH2Ortvcnk14IVwPYJkLA9Ev1iSVPx13g8AIBPN5TF94FVhuIgYXco7LIJGqPpJ++cKeITJ1bdLVtAZnC7CQlQ2CVyxitwyHuthceX9hkmyU9KJUDYERyDraO/MqqpzE1Ob1WfLrDVjY/p2TPhkL55dp77xiRxU3pBDOGhD4GzZo2Da23l9uwoNyYZlzuHhFYASCKQmvcsrFM58PkWXb5BsFch+e28N5DYXkmY26h8ilfSKkce+wMVIc05J/rSpsNkq8+6gyAiOQEYvUMTF5ZETMVa4SWAfUb1deF9hiERluf1LfJtEWgREI/Ap4FVRK1m8bMpIAuQHieh2t+AjgldggkEkVrTICI5By+4DcPThqRGORBYLJPTTcW6Buv9DJsc0PCIxA8snSmg8RHQQn+G6AHR1Emuc9Lyi8sGdYyVi7bhEYgcCRh1dRxSKmD8hChbQKbvDJ8oRh4s57ZlB4QusQ2VAiA8xiIzAC+biEQZn/2iNkOAu5Ac5pECCB97wgEVu6SCsdFARGIED7ccUdRRAE+/VZ7tMbrNxZVba0A6VmzykBmFcxCJRAcIp8z5DCH5Qd3bLCyH/u1u4I79NvRqJoedNVIzYdgmbMGCiBAJjKIFc3rwLdEtMFpGvb6MGxaNO+atKkn9rGk4UkLABwoh80BE4gAELp5LNLhAU4nIswNXIL5AFEfvXjnq0dUyoQp/qV/t/R5SKQAgH20umQ2/izcOmFI5PXfOird1UZXoK8ZweVMKgUxfbyOwIrEAAOVjKLY/i7I2cFAtV5AULgdBgXN9YqvOcHlRe/HDZSKQQZgRYIgIAPqEheBcNHAxmonLJUiQDTctgb8Z4fZGKdl0+5+QWBFwgAX4zrX0+L5LhnQuTB4VHy1fpUXjsuiC5/zWu1azpl8raBERJWO6RuwVArBAJgh2XCylTei0lEbsR2Jna4eI0n6Gw+OmYkAq0tqDUCyRcIiYPkl/DH4DWcoBMWx2/OriXDBgMtEAdAGFiAYyHPazi1gUiXhilpbYQWiA22HagyzLWRmZbXaGoLsXZzCrcUZGiBWLBka4rc/17UUxypIBHmMTCTqUXLDS60QDLArhROhHmNpbbx0t4RsvaHYJir5wstkAyw5fv+wkTZ0yOXk/BTgQtwPvG4ggYtEAtgNtHq01itOhXHlvVjI+EyXMvnUxxogdgAHnGw5A36ecetb0WMlNsafGiBOAAGiDBgLEROPlUIa+XbBkaNYHMaYmiBSAL+HTBo/I2P/cmRAPXRkTGyRi/ApaEF4hIVMULenpsgjV9RL8SnHeFDj7hhMNzUcActkDyAeMDdP4+79jspBRt2C5EO46Lk6+16tMgHWiAFAvL9IaDDrQMjRh4QXqMtJnHif+MbEdJnelyfYRQQWiBFAKKeLKc9N9KeYc5/0cthOv8v3CL/WPosuBTDqhiixGI7iP7gKkALpESAyQbsuxCoeuTiJOk9LU7ajo0b6c3ueydK7hgUIbe8GTFGoDsHR43k/I/T79qMjZFXpiXI8IUJIwf5lv1Vtd78o5TQAtHQEEALRENDAC0QDQ0BtEA0NATQAtHQEEALRENDAC0QDQ0BAi0QpE2e9X3KoDa5KCw278uWLc5nVAQOUD9fnea0b91lATMRaIFc1z9rI4UgbxqFA2zQzLKF/76KuOnNrAt1vbahzKfuoAWi4QlaIAGAFkjxoAUSANQWgSzdVkX6zkgcYSSRv7EWgnKbzxu5uGZaNT8IZMfBasMlAVzvMamoFkgAgPhV5u8EC+EYdcOAbMJRRMe3wg8CKQS0QAIALZDi4YhAtu6vIgs2pci8jWni/+0SyiD6oHndhr25lYF8fuZ3i7fm3v8tHerM78xt1+9/TH82n/L7PdVEVLUw9TbfEZE4YPaNe8xnLtuWu93oJJDtB7PvA/4UzXxBgThZcILCe7HXzKd/Hw5JvNhRWw9k3wXvCcA3ZNGWFFmyJX3DgXD2GhDR5vHZwszvwm9AQh4ZHI6kn9Xio2xjBT9fnTQ+X0fL1i3QDnDvxb2zZYc8KvgMNEMD8QSCKY1ZXqifRMq+NmNJQr7ZkVv+4FLatpCuwg6IlbyYlqV5vag+RG0DwF/BNWwdox52Hco+rM5u+oOv6JstDCsv6BWmjT73hf/QJesx98SHufkE2IT+CHrM4h9Dsr3SeT1DOf82eTatDAiJBQrlqldrRj2EIxJ8J8x/414WTgK5nPndp3QIkWhmqxzCOK+nOMoikuZYc6V3mpBtNHCQQgdzVrd0WeFdgclrUkeuAXGPNWI8vAPhCOUEVCh7n5X/HMooXhJdJopTaQ+dl34vq0C6TooZ0VLYa1H/09fVbJgfLEmQ3z2Xvc7KY1pUkM4Tc3sJCAohYe3CMJ3aqdI4k2HRdFj2tzTqnrtIR/7JRrS9sM9giQU+YqTVuZcWIu8ClsjWyqIQAkGhmv9vJUJfsnhkhP07ss9xIxBr48I0xcTV9Fr2OztCVAmmTqwCuZzJtmsnELtyQGNb5ZBEVBWB/Iw2WruwSNg9YjcNMMoc07LmdTxOXJk93IODGe8alvXaVhpZjk2IBHJuD+c6bjYqSuqc0Drb2C/ohegXCfIaJZvCGAXAZhQqhEBAqPS/o2LGM87okqtmdrrDpjir2waha6LGffDEYyvGjUBuH5T9fahEM7EORhG2l0KOQ/RmaDhd6H+v6pf97SB7Qs8KxORpHdN/+8lMOVkF0oCWJX4/fg98ytnvBjiMIhjpcJ81cShccfH5kExjdoMJtFHi3lPpe5vPq9+2wvgMhCgBViAgOjXzGrQj9ruFm7O9yAeLc9dLqMN02cZo28mtT7QlE2xdomOCYJA+D8H9zM/BBZuy9WEnkF2HqnPuQQrr/jMTpO/0uDGdND9v2C1M6rAXIi6riU+/Th75HNxDpzkmCiGQM+gzWAyZl/v3dtIfYeIEZjh++pPcoRcB0MzvZAWCOSs7HXhxcvaZWOCan4Pvzs9tZKhs9ns2b4ZVIM1oY7G6x1oFMvO77P0Yjdjv2PcSodyLdJRlBbNuwLrA/A6c9m32N8JPn/0OazQWbNLVpsOyvSSbZ/Jh2gGYgMmL+Tn4xZrsqGMnEEzh2XvYOniBlrn5OTrOHIEMmpNtDGNXFFcgCDrAYthCOYHAj5sFWwiyAnmYmbL9tlVuGmOrQOALzmLZttzCFQkE6zsrrAJBcAcW7Hd+EYi5SDeBTRzzO9BOIJiZWMHmt7cTCOIIm8Cmgvk56EUgbB32+EJSINgVwLTKJJvw0s8CwRyYDUzdkTZqFoUSCPJr8FAOgeBf2CkTEYtgFn4RCH4b207Z3SwvAsEobj4L6xlbgYjgZ4G0HpO9HgtpdmQECiUQPJuHcgjE+pt4RPmz8ItARPAiECvqsL1pc9q4sbeO+WRlrNo2vIxfBYKpFBvU7elPct8d0AJJo1QCwaKf5ZnPZ+uMFQi7EYENJPymdDtNnzXxYCcQnN2Zn4MD6GIfIWXxPJxBVTPTpTo4j2AvZolgx/cMCdeYS/tVIK9My1YqdqpwUGhFEAWCRoQzBBGtvWgpBOJEViAIwMe7BsTfxzkZ/H9Y2AkE00nky2efwRI7u9hgwTSrzji6GHcK7c8ucAG/CmTMityKm2M56AOCKBAvUE0g2HlkjyR4PKldJR0Bsr/dTiBA72nO74EZlWFqglNF7PHjQA576CC7HwziNNuEXwWCoRjnEuZndw+uOZfVAkmjVFOscd8kbYmyZrGDjvi9pqajUZrtlD2MBacyf0skEAAn74hciV1NPAvXn0LbrHkP0vHZGivOWJf7I1nzDz8v0l9itvEwzbLam2mBpFGuRbpbWOvrwyXO27wiwMTHvAfnO7YCgZ2ReSHIRgz3s0AwEmIL1vwc+QhZaIGk4ReBYGHN/q0PFucnkMFzcsuyTofxcdLi46jBKWuzPySoAgEwtzU/R8Yo7NyZUFUgoVjuuQUbzT1IArl7cJhcSadNIGsqM/CrbDsdMjf7uReBVNJ7zGeBK3Zk36+GQOrTeZb5D7ZCZAXy+MjcBfxTo+UE8rcCCeR+DwJBtAvzcxB2OCZUFQh2VdjvYOlgwiqQfQUWyEU9SycQdo3YeWK282XdZ2HBbcKLQDCLYO8Zw5RlDYGgEZv/wCK9KrMHPHxRboP9jvEtgBGX+Xnj3hHjuy37q43F/l9ezH4nEgi2kNPh/KuN/H8YiczvQHZruV7r7OfX0kYPHxLcB0NBVqyyAgEaM/4ODbqEj5zA4qzE/BxsQwVpng3BTwHp19jvTeM9oFwCgVEj+x0WsjC5yCfUEdsgkT8dLrh45vYD6Wd6FYi1/JZsrTLKFoRbLNqF+V23SVmBsDZ3sIyOZx4Ji2fzc3D0UmeBWDtBJB0C0PTbj8v+Luzu1mGtds0Pj7aYI2POjj1hE1arUzuKBCIiKoQ1GYClKO86K90IBH7W7L3YNQFQSPXbZUUnInrAHw5nhVwugVifadKLubsJJCzlPdPOH4SFSCBfrsvteEVEHhUTWCuy32GDBYfcVh8U/G0TdgJBjcHOir0PvwFkP8NObh14nzmdg3SgqmIxdS3/Hrys7AiCodQuYywMxljAshiN0XodCondjnYjEBwWndg++yzW58U6ZbEjDq9YlEsgsB+6hBkRTeYjEIzSvHOHfAWCjo91VLMj6pX1rMTpt9M5yA0Dwjk2g3YCAeDWwd5rJdryiEWJ9C4Whjn0GHcOjpA7BiHbUZqPjIgZjZP9oyaW0Hk8FuSYD+Ja5BJHpWEINe9/cHhuBVkX6XCDRCNj/57Zk1sxdwN8H6JH/h5OfzHk44ea9+Ngh0WXSfEj33WyeKgB7LuCpjspgI4DNj/I/MReA+J3oXdjRzkAn5nX2DVOrGHYZ8FFmQX73UfLsmUBOzn2O9Ol1wQaE6ZaqAfzGhyG5QNMY+ELcw+tN/OZZmPHVMb87C66sGaBqZL5HWid6mE2gu1U9l1N3js0Yrw3a2FtAu+DToh9HxBtAeVjNbhk2wacn6z4Ym3KWEOzdYz2hc7IXFvabvMWA1aBaGioDi0QDQ0BtEA0NATQAtHQEEALRENDgJIKBLsXhyNpmlFENDRURkkFoqHhN2iBaGgIoAWioSGAFoiGhgBaIBoaAmiBaGgIoAWioSGAFoiGhgBaIBoaAmiBaGgIoAWioWELQv4f+attZEP3sqMAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - cache.quay.io
          resources:
          - dns
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.quay.io
          resources:
          - dns/finalizers
          verbs:
          - update
        - apiGroups:
          - cache.quay.io
          resources:
          - dns/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - cache.quay.io
          resources:
          - dnsrecords
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cache.quay.io
          resources:
          - dnsrecords/finalizers
          verbs:
          - update
        - apiGroups:
          - cache.quay.io
          resources:
          - dnsrecords/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: coredns-integration-operator-controller-manager
      deployments:
      - name: coredns-integration-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/linxianer12/coredns-integration-operator:0.0.7
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: coredns-integration-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: coredns-integration-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - network
  links:
  - name: Coredns Integration Operator
    url: https://coredns-integration-operator.domain
  maintainers:
  - email: 6370279821@student.chula.ac.th
    name: supakorn.trakulmaiphol
  - email: wdrdres3qew5ts21@gmail.com
    name: supakorn.trakulmaiphol
  maturity: alpha
  provider:
    name: supakorn.t-thesis
  version: 0.0.1
