# permissions for end users to view dns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-viewer-role
rules:
- apiGroups:
  - cache.quay.io
  resources:
  - dns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.quay.io
  resources:
  - dns/status
  verbs:
  - get
