# permissions for end users to edit dns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-editor-role
rules:
- apiGroups:
  - cache.quay.io
  resources:
  - dns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.quay.io
  resources:
  - dns/status
  verbs:
  - get
