apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: coredns-integration-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.quay.io
      version: v1alpha1
  description: CoreDNS for mapping DNS Record like using in On-Premise Platform
  displayName: coredns-integration
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - network
  links:
  - name: Coredns Integration Operator
    url: https://coredns-integration-operator.domain
  maintainers:
  - email: wdrdres3qew5ts21@gmail.com
    name: supakorn.trakulmaiphol
  maturity: alpha
  provider:
    name: supakorn.t-thesis
  version: 0.0.0
