apiVersion: cache.quay.io/v1alpha1
kind: DNS
metadata:
  name: napzz
  namespace: private-dns
spec:
  domainZones:
    - dnsRecord:
        - name: web
          target: 192.168.18.5
          type: A
        - name: crm
          target: 192.168.18.4
          type: A
      name: napzz-company.local
    - dnsRecord:
        - name: web
          target: 192.168.18.4
          type: A
        - name: backend
          target: 192.168.18.5
          type: A
      name: thesis.local
